### ISSUE TITLE
Cannot generate the same RMSE as in the paper

### ISSUE THREAD

**Issue by RobinloveCode** [yangysc/HFCM#2]
Thanks for sharing the codes which are very helpful.

However, I fail to generate the same results as in the paper (RMSE), although I set the same hyper-parameters.

**Comment by yangysc** [comment]
Hi, Robin. Thanks for your interests for our work.  Did you run the code without modifications? Maybe the variance is due to the library version? Could you share the your results?

**Comment by RobinloveCode** [comment]
@yangysc 
Many thanks for your response. I ran the code without modifications. Take Dow J series as an example. 
I set the split schemes as in the paper:
Train dataset length is 175
Validation dataset length is 43
Test dataset length is 73
order=3 Nc=4 and alpha=1e-20

The RMSE is different from the paper, but they are very similar.
My outcomes are test RMSE 26.715 validation RMSE 30.527 train RMSE 26.237.
Results in paper: test RMSE 23.159 validation RMSE 23.171 train RMSE 23.216.

Since I want to cite your work and compare with your results, I need to clarify everything. Otherwise I may use different datasets.

Could you share the numerical forecasts of all time series if you have stored the results before. 

Thanks a lot.

**Comment by yangysc** [comment]
Hi, I am so sorry for your problem, but I didn't store the numerical results. I just run the same configuration as yours, and I obtain slightly different results.
For DJ series,
`The ratio is 0.750000
best Order is 3, best Nc is 4, best alpha is 1e-20
Forecasting on all dataset: MSE|RMSE|NMSE is : |629.261174 |25.085079 |0.000185|
Forecasting on train dataset: MSE|RMSE|NMSE is : |586.629297 |24.220431 |0.000251|
Forecasting on validation dataset: MSE|RMSE|NMSE is : |748.778792 |27.363823 |0.005731|
Forecasting on test dataset: MSE|RMSE|NMSE is : |661.060088 |25.711089 |0.001766|
The whole length is 291
Train dataset length is 175
Validation dataset length is 43
Test dataset length is 73
`

So I think python libraries versions may lead to this variance. I suggest that you can use grid search to find the optimal results for your python configuration.
For my current python configuration (different from my original one)
`The ratio is 0.750000
best Order is 3, best Nc is 7, best alpha is 1e-20
Forecasting on all dataset: MSE|RMSE|NMSE is : |419.069120 |20.471178 |0.000134|
Forecasting on train dataset: MSE|RMSE|NMSE is : |319.796169 |17.882846 |0.000144|
Forecasting on validation dataset: MSE|RMSE|NMSE is : |561.574699 |23.697567 |0.006173|
Forecasting on test dataset: MSE|RMSE|NMSE is : |573.110581 |23.939728 |0.001775|
The whole length is 291
Train dataset length is 175
Validation dataset length is 43
Test dataset length is 73`

Hope this can help you.

**Comment by RobinloveCode** [comment]
@yangysc Many thanks. I need to reoptimize the hyperparameters. 
The ratio is 0.750000 best Order is 3, best Nc is 7, best alpha is 1e-20 
I generate the same results as yours

**Comment by yangysc** [comment]
Good luck with your paper!
