### ISSUE TITLE
What is the meaning of steepness in the program?

### ISSUE THREAD

**Issue by RobinloveCode** [yangysc/HFCM#3]
During the training process, the steepness value of tanh function is 1 by default, however, in prediction process, the steepness values are set as :
                steepness = np.max(np.abs(W_learned), axis=1)
                for i in range(Nc):
                    if steepness[i] > 1:
                        W_learned[i, :] /= steepness[i]

I am confused about this. Because it is not consistent with training target. Looking forward to your reply.

**Comment by yangysc** [comment]
Actually it is not involved in the later calculation.
